In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
path = "../data/raw"

In [4]:
status = pd.read_csv(path + "/status.csv")
status.head()


qualifying = pd.read_csv(path + "/qualifying.csv")
qualifying.head()
drivers = pd.read_csv(path + "/drivers.csv")
drivers.head(15)

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
5,6,nakajima,\N,NAK,Kazuki,Nakajima,1985-01-11,Japanese,http://en.wikipedia.org/wiki/Kazuki_Nakajima
6,7,bourdais,\N,BOU,Sébastien,Bourdais,1979-02-28,French,http://en.wikipedia.org/wiki/S%C3%A9bastien_Bo...
7,8,raikkonen,7,RAI,Kimi,Räikkönen,1979-10-17,Finnish,http://en.wikipedia.org/wiki/Kimi_R%C3%A4ikk%C...
8,9,kubica,88,KUB,Robert,Kubica,1984-12-07,Polish,http://en.wikipedia.org/wiki/Robert_Kubica
9,10,glock,\N,GLO,Timo,Glock,1982-03-18,German,http://en.wikipedia.org/wiki/Timo_Glock
10,11,sato,\N,SAT,Takuma,Sato,1977-01-28,Japanese,http://en.wikipedia.org/wiki/Takuma_Sato
11,12,piquet_jr,\N,PIQ,Nelson,Piquet Jr.,1985-07-25,Brazilian,"http://en.wikipedia.org/wiki/Nelson_Piquet,_Jr."
12,13,massa,19,MAS,Felipe,Massa,1981-04-25,Brazilian,http://en.wikipedia.org/wiki/Felipe_Massa
13,14,coulthard,\N,COU,David,Coulthard,1971-03-27,British,http://en.wikipedia.org/wiki/David_Coulthard
14,15,trulli,\N,TRU,Jarno,Trulli,1974-07-13,Italian,http://en.wikipedia.org/wiki/Jarno_Trulli

In [5]:
seasons = pd.read_csv(path + "/seasons.csv")
seasons.head()
#Will not be used. Too few meaningful data

   year                                                url
0  2009  http://en.wikipedia.org/wiki/2009_Formula_One_...
1  2008  http://en.wikipedia.org/wiki/2008_Formula_One_...
2  2007  http://en.wikipedia.org/wiki/2007_Formula_One_...
3  2006  http://en.wikipedia.org/wiki/2006_Formula_One_...
4  2005  http://en.wikipedia.org/wiki/2005_Formula_One_...

In [6]:
sprint = pd.read_csv(path + "/sprint_results.csv")
sprint.info()
sprint.head()

#Although the impact is not significant can be helpful when seeing the results of a driver on a short distance.

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   resultId        360 non-null    int64
 1   raceId          360 non-null    int64
 2   driverId        360 non-null    int64
 3   constructorId   360 non-null    int64
 4   number          360 non-null    int64
 5   grid            360 non-null    int64
 6   position        360 non-null    str
 7   positionText    360 non-null    str
 8   positionOrder   360 non-null    int64
 9   points          360 non-null    int64
 10  laps            360 non-null    int64
 11  time            360 non-null    str
 12  milliseconds    360 non-null    str
 13  fastestLap      360 non-null    str
 14  fastestLapTime  360 non-null    str
 15  statusId        360 non-null    int64
dtypes: int64(10), str(6)
memory usage: 45.1 KB

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1

In [12]:
sprint.loc[19]

resultId                20
raceId                1061
driverId               815
constructorId            9
number                  11
grid                     5
position                \N
positionText             R
positionOrder           20
points                   0
laps                    16
time                    \N
milliseconds            \N
fastestLap               6
fastestLapTime    1:31.465
statusId                76
Name: 19, dtype: object

In [13]:
results = pd.read_csv(path + "/results.csv")
results.info()
results.loc[1062]

<class 'pandas.DataFrame'>
RangeIndex: 26759 entries, 0 to 26758
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         26759 non-null  int64
 1   raceId           26759 non-null  int64
 2   driverId         26759 non-null  int64
 3   constructorId    26759 non-null  int64
 4   number           26759 non-null  str
 5   grid             26759 non-null  int64
 6   position         26759 non-null  str
 7   positionText     26759 non-null  str
 8   positionOrder    26759 non-null  int64
 9   points           26759 non-null  float64
 10  laps             26759 non-null  int64
 11  time             26759 non-null  str
 12  milliseconds     26759 non-null  str
 13  fastestLap       26759 non-null  str
 14  rank             26759 non-null  str
 15  fastestLapTime   26759 non-null  str
 16  fastestLapSpeed  26759 non-null  str
 17  statusId         26759 non-null  int64
dtypes: float64(1), int64(8), str(9)
memory usage: 3.7 MB

resultId               1063
raceId                   67
driverId                 26
constructorId             5
number                   21
grid                     15
position                 13
positionText             13
positionOrder            13
points                  0.0
laps                     52
time                     \N
milliseconds             \N
fastestLap               50
rank                     18
fastestLapTime     1:25.094
fastestLapSpeed     245.079
statusId                 11
Name: 1062, dtype: object

In [14]:
races = pd.read_csv(path + "/races.csv")
races_preprocessed = races[["raceId", "year", "round", "circuitId", "name"]]
races_preprocessed.to_csv("../data/preprocessed/races_prep.csv")

In [18]:
races.info()
races.loc[1046]

<class 'pandas.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1125 non-null   int64
 1   year         1125 non-null   int64
 2   round        1125 non-null   int64
 3   circuitId    1125 non-null   int64
 4   name         1125 non-null   str
 5   date         1125 non-null   str
 6   time         1125 non-null   str
 7   url          1125 non-null   str
 8   fp1_date     1125 non-null   str
 9   fp1_time     1125 non-null   str
 10  fp2_date     1125 non-null   str
 11  fp2_time     1125 non-null   str
 12  fp3_date     1125 non-null   str
 13  fp3_time     1125 non-null   str
 14  quali_date   1125 non-null   str
 15  quali_time   1125 non-null   str
 16  sprint_date  1125 non-null   str
 17  sprint_time  1125 non-null   str
dtypes: int64(4), str(14)
memory usage: 158.3 KB

raceId                                                      1061
year                                                        2021
round                                                         10
circuitId                                                      9
name                                          British Grand Prix
date                                                  2021-07-18
time                                                    14:00:00
url            http://en.wikipedia.org/wiki/2021_British_Gran...
fp1_date                                              2021-07-16
fp1_time                                                      \N
fp2_date                                              2021-07-17
fp2_time                                                      \N
fp3_date                                                      \N
fp3_time                                                      \N
quali_date                                            2021-07-16
quali_time                                                    \N
sprint_date                                           2021-07-17
sprint_time                                                   \N
Name: 1046, dtype: object