In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
path = "../data/raw"

In [ ]:
status = pd.read_csv(path + "/status.csv")
status.head()



drivers = pd.read_csv(path + "/drivers.csv")
drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [8]:
seasons = pd.read_csv(path + "/seasons.csv")
#Will not be used. Too few meaningful data

In [9]:
sprint = pd.read_csv(path + "/sprint_results.csv")
sprint.info()
sprint.head()

#Although the impact is not significant can be helpful when seeing the results of a driver on a short distance.

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   resultId        360 non-null    int64
 1   raceId          360 non-null    int64
 2   driverId        360 non-null    int64
 3   constructorId   360 non-null    int64
 4   number          360 non-null    int64
 5   grid            360 non-null    int64
 6   position        360 non-null    str
 7   positionText    360 non-null    str
 8   positionOrder   360 non-null    int64
 9   points          360 non-null    int64
 10  laps            360 non-null    int64
 11  time            360 non-null    str
 12  milliseconds    360 non-null    str
 13  fastestLap      360 non-null    str
 14  fastestLapTime  360 non-null    str
 15  statusId        360 non-null    int64
dtypes: int64(10), str(6)
memory usage: 45.1 KB

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1

In [12]:
results = pd.read_csv(path + "/results.csv")
results.info()

<class 'pandas.DataFrame'>
RangeIndex: 26759 entries, 0 to 26758
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         26759 non-null  int64
 1   raceId           26759 non-null  int64
 2   driverId         26759 non-null  int64
 3   constructorId    26759 non-null  int64
 4   number           26759 non-null  str
 5   grid             26759 non-null  int64
 6   position         26759 non-null  str
 7   positionText     26759 non-null  str
 8   positionOrder    26759 non-null  int64
 9   points           26759 non-null  float64
 10  laps             26759 non-null  int64
 11  time             26759 non-null  str
 12  milliseconds     26759 non-null  str
 13  fastestLap       26759 non-null  str
 14  rank             26759 non-null  str
 15  fastestLapTime   26759 non-null  str
 16  fastestLapSpeed  26759 non-null  str
 17  statusId         26759 non-null  int64
dtypes: float64(1), int64(8), str(9)
memory usage: 3.7 MB

In [13]:
races = pd.read_csv(path + "/races.csv")
races_preprocessed = races[["raceId", "year", "round", "circuitId", "name"]]
races_preprocessed.to_csv("../data/preprocessed/races_prep.csv")

In [14]:
races.info()
races.loc[1046]

<class 'pandas.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1125 non-null   int64
 1   year         1125 non-null   int64
 2   round        1125 non-null   int64
 3   circuitId    1125 non-null   int64
 4   name         1125 non-null   str
 5   date         1125 non-null   str
 6   time         1125 non-null   str
 7   url          1125 non-null   str
 8   fp1_date     1125 non-null   str
 9   fp1_time     1125 non-null   str
 10  fp2_date     1125 non-null   str
 11  fp2_time     1125 non-null   str
 12  fp3_date     1125 non-null   str
 13  fp3_time     1125 non-null   str
 14  quali_date   1125 non-null   str
 15  quali_time   1125 non-null   str
 16  sprint_date  1125 non-null   str
 17  sprint_time  1125 non-null   str
dtypes: int64(4), str(14)
memory usage: 158.3 KB

raceId                                                      1061
year                                                        2021
round                                                         10
circuitId                                                      9
name                                          British Grand Prix
date                                                  2021-07-18
time                                                    14:00:00
url            http://en.wikipedia.org/wiki/2021_British_Gran...
fp1_date                                              2021-07-16
fp1_time                                                      \N
fp2_date                                              2021-07-17
fp2_time                                                      \N
fp3_date                                                      \N
fp3_time                                                      \N
quali_date                                            2021-07-16
quali_time                                                    \N
sprint_date                                           2021-07-17
sprint_time                                                   \N
Name: 1046, dtype: object

In [24]:
drivers["fullName"] = drivers["forename"] + " " + drivers["surname"] 

driver_standings = pd.read_csv(path + "/driver_standings.csv")
driver_standings = pd.merge(driver_standings, drivers, left_on="driverId", right_on="driverId")[["driverStandingsId", "raceId", "driverId", "points", "position", "positionText", "wins", "driverRef", "fullName"]]
driver_standings.to_csv("../data/preprocessed/driver_standings_prep.csv")

In [ ]:
qualifying = pd.read_csv(path + "/qualifying.csv")

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236
...,...,...,...,...,...,...,...,...,...
10489,10547,1144,848,3,23,16,1:23.821,\N,\N
10490,10548,1144,855,15,24,17,1:23.880,\N,\N
10491,10549,1144,1,131,44,18,1:23.887,\N,\N
10492,10550,1144,861,3,43,19,1:23.912,\N,\N
10493,10551,1144,862,214,61,20,1:24.105,\N,\N

In [5]:
races

NameError: name 'races' is not defined